### ISSUE TITLE
Unable to install PGCGAP

### ISSUE THREAD

**Issue by oisinskinnader** [liaochenlanruo/pgcgap#1]
After install conda and using the following commands:
$conda config --add channels defaults
$conda config --add channels bioconda
$conda config --add channels conda-forge

I created a pgcgap environment for the installation of PGCGAP.
$conda create -n pgcgap python=3
Activated the pgcgap environment.
$conda activate pgcgap
However, during Installation of PGCGAP using:
$conda install pgcgap
I get the following issue:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Where am I going wrong? What should I do?

Thanks,

Oisin

**Comment by liaochenlanruo** [comment]
> After install conda and using the following commands:
> $conda config --add channels defaults
> $conda config --add channels bioconda
> $conda config --add channels conda-forge
> 
> I created a pgcgap environment for the installation of PGCGAP.
> $conda create -n pgcgap python=3
> Activated the pgcgap environment.
> $conda activate pgcgap
> However, during Installation of PGCGAP using:
> $conda install pgcgap
> I get the following issue:
> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> Where am I going wrong? What should I do?
> 
> Thanks,
> 
> Oisin
> 

- Have a try with the following command:

conda install pgcgap=1.0.30


- or remove the pgcgap environment with the command:

conda remove -n pgcgap --all

and then run:

conda create -n pgcgap pgcgap

- If it does not work, please let me know.

**Comment by oisinskinnader** [comment]
> > After install conda and using the following commands:
> > $conda config --add channels defaults
> > $conda config --add channels bioconda
> > $conda config --add channels conda-forge
> > I created a pgcgap environment for the installation of PGCGAP.
> > $conda create -n pgcgap python=3
> > Activated the pgcgap environment.
> > $conda activate pgcgap
> > However, during Installation of PGCGAP using:
> > $conda install pgcgap
> > I get the following issue:
> > Collecting package metadata (current_repodata.json): done
> > Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> > Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> > Collecting package metadata (repodata.json): done
> > Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> > Solving environment: |
> > Found conflicts! Looking for incompatible packages.
> > This can take several minutes.  Press CTRL-C to abort.
> > failed
> > UnsatisfiableError: The following specifications were found to be incompatible with each other:
> > Output in format: Requested package -> Available versions
> > Where am I going wrong? What should I do?
> > Thanks,
> > Oisin
> 
> * Have a try with the following command:
> 
> conda install pgcgap=1.0.30
> 
> * or remove the pgcgap environment with the command:
> 
> conda remove -n pgcgap --all
> 
> and then run:
> 
> conda create -n pgcgap pgcgap
> 
> * If it does not work, please let me know.

Here is how it went: 
**(pgcgap) C:\Users\oisin>conda install pgcgap=1.0.30
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions


(pgcgap) C:\Users\oisin>conda remove -n pgcgap --all

CondaEnvironmentError: cannot remove current environment. deactivate and run conda remove again

(pgcgap) C:\Users\oisin>conda create -n pgcgap pgcgap
WARNING: A conda environment already exists at 'C:\Users\oisin\miniconda3\envs\pgcgap'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:**

Not really sure what the problem is.

**Comment by liaochenlanruo** [comment]
@oisinskinnader
- Before you remove an environment, you should first deactivate it. So what you need to do is shown as following:
```bash
conda deactivate pgcgap
conda remove -n pgcgap --all
conda create -n pgcgap pgcgap
```

**Comment by oisinskinnader** [comment]
> @oisinskinnader
> 
> * Before you remove an environment, you should first deactivate it. So what you need to do is shown as following:
> 
> ```shell
> conda deactivate pgcgap
> conda remove -n pgcgap --all
> conda create -n pgcgap pgcgap
> ```

No, I did try deactivate it but got the following:

(pgcgap) C:\Users\oisin>conda deactivate pgcgap
deactivate does not accept arguments
remainder_args: ['pgcgap']

I think did those commands but to no avail.

**Comment by liaochenlanruo** [comment]
@oisinskinnader
Sorry,  please type 

"conda deactivate" instead of "conda deactivate pgcgap"

**Comment by oisinskinnader** [comment]
> @oisinskinnader
> Sorry, please type
> 
> "conda deactivate" instead of "conda deactivate pgcgap"

Yeah that worked but there's still problems.

(pgcgap) C:\Users\oisin>conda deactivate

(base) C:\Users\oisin>conda remove -n pgcgap --all

DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: C:\Users\oisin\miniconda3\envs\pgcgap



(base) C:\Users\oisin>conda create -n pgcgap pgcgap
WARNING: A directory already exists at the target location 'C:\Users\oisin\miniconda3\envs\pgcgap'
but it is not a conda environment.
Continue creating environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

**Comment by liaochenlanruo** [comment]
@oisinskinnader
Do you have any software installed which can be connected remotely to your computer, that I can install PGCGAP for you?
Such as teamviewer

**Comment by oisinskinnader** [comment]
> @oisinskinnader
> Do you have any software installed which can be connected remotely to your computer, that I can install PGCGAP for you?
> Such as teamviewer

Yes.  I just sent you an email about that.

Thanks.

**Comment by liaochenlanruo** [comment]
@oisinskinnader
PGCGAP v1.0.31 is available, I have re-submitted an environmental file to Conda to accelerate installation speed, and there are some instructions to solve the installation problems which can be found at https://liaochenlanruo.github.io/pgcgap/#Installation
